config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'
  resources :pizzas, only: [:index, :show] do
  resources :orders, only: [:create]

end
  get '/question', to: 'pages#question'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :pizza
  has_many :pizzas
end

app/models/order_pizza.rb
class OrderPizza < ApplicationRecord
  belongs_to :pizza
  belongs_to :order
end

app/models/pizza.rb
class Pizza < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new
  end

  def create
  @order = Order.new(params_order)

  if @order.save
      redirect_to home_path, notice: 'order was successfully created.'
    # else
    #   render :new
    end
  end

  def params_order
      params.require(:order).permit(:t_quantity, :comment, :t_price, :delibery_date, :customer_name, :customer_lname, :customer_phone, :customer_mail, :customer_street, :customer_floor, :customer_zip)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

  def index
    @pizzas = Pizza.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gulapizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
<%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>
<!--    <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
hola
`

app/views/orders/new.html.erb
<!-- t.integer "t_quantity"
    t.integer "t_price"


    t.bigint "pizza_id", null: false
    t.bigint "customer_id", null: false -->

app/views/pages/about.html.erb
<div class="colorwhite">
  <div class="container">
    <h2 class="about_title">NUESTROS SERVICIOS</h2>
    <h2 class="subtitle-about">PIZZAS CASERAS LISTAS PARA HORNEAR</h2>
    <p class="text-about">DÍAS DE ENTREGA VIERNES, SÁBADO Y DOMINGO <br>DE 17 A 19.30HS.<br>
    LOS PEDIDOS SE PUEDEN REALIZAR TODOS LOS DÍAS<br> DE LA SEMANA <br>
    SI EL PEDIDO ES PARA EL MISMO DÍA, SE PODRÁ REALIZAR<br>
    HASTA LAS 15HS.
    <br>
    <br>
    PARA EVENTOS ESPECIALES CONTACTARSE AL 655 536 287</p>

    <div class="image_footer">
      <a href="/">
      <%= cl_image_tag("logo_gpvujf",
      width: 100, height:150, ) %>
    </a>
     </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="colorwhite">
<div class="container">
  <div class="menu_home_list">
     <div><%= link_to "NUESTRAS PIZZAS", pizzas_path, class: "btn-dark menu_home"%></div>
     <div><%= link_to "NUESTROS SERVICIOS", about_path, class: "btn-dark menu_home"%></div>
     <div><%= link_to "PREGUNTAS FRECUENTES", question_path, class: "btn-dark menu_home"%></div>
    </div>
    <div>
     <p>   <%= link_to "HAZ TU PEDIDO", pizzas_path, class: "btn button_pedido"%></p>
    </div>


<!--       <%= cl_image_tag("gulabanner_dsjmml",
       :width=>"auto:90:900", :crop=>"scale", :use_root_path=>true, :client_hints=>true) %> -->
       <img src="https://res.cloudinary.com/djrxx3xla/image/upload/v1605643899/gulabanner_dsjmml.png" alt="" class="cld-responsive">

    <div class="slogan">
      <p>PIZZAS DE VERDAD</p>
    </div>
    <div class="home_icons">
      <a href="https://www.instagram.com/lagula_pizza/?hl=es"target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://wa.me/<34655536287>"target="_blank"><i class="fab fa-whatsapp"></i></a>
    </div>
    <div class="zonas">
       <p>CASTELLDEFELS - GAVÀ MAR - LES BOTIGUES</p>
    </div>
    <div class="envio">
      <p>ENVÍO SIN CARGO</p>
    </div>
  </div>
 </div>

app/views/pages/question.html.erb
<div class="colorwhite">
  <div class="container">
    <h2 class= "title_question">PREGUNTAS FRECUENTES</h2><br>
    <div class="question_list">
      <ul>
        <li>SE PUEDEN FREEZAR?<br>
          Sí, se pueden freezar porque todas nuestras  pizzas están elaboradas con
          Productos frescos. Es preferible quitarla de la caja y cubrirla por completo con papel film.</li><br><br>
        <li>PUEDO REALIZAR UN PEDIDO DESPUÉS DE LAS 16HS?<br>
          En este caso es mejor enviar un mensaje a nuestro whatssap 655 536 287
          Para ver si tenemos disponible el producto que solicitas.</li><br><br>
        <li>PUEDO COORDINAR OTRO HORARIO DE ENTREGA?<br>
          Si tienes alguna preferencia en el horario de entrega, puedes aclararlo
          En comentarios a la hora de hacer el pedido.</li><br><br>
          <li>SE REALIZAN PEDIDOS PARA EVENTOS?<br>
          Sí, es posible hacer pedidos para eventos, a través de nuestro whatssap 655 536 287.
          con dos días de anticipación como mínimo, para darte un buen servicio.</li><br><br>
      </ul>
    </div>
  </div>
<!--  <%= link_to " ", root_path, class: "image_footer"%> -->
<!--    <div class="image_footer">
    <a href="/">
       <img src="https://res.cloudinary.com/djrxx3xla/image/upload/v1605643870/logo_gpvujf.png" alt="" >
    </a>
     </div> -->
         <div class="image_footer">
      <a href="/">
      <%= cl_image_tag("logo_gpvujf",
      width: 100, height:150, ) %>
    </a>
     </div>

</div>

app/views/pizzas/index.html.erb
<div class="colorwhite">
  <div class="container">
    <h2 class= "title_index">NUESTRAS PIZZAS</h2>
    <P class="subtitle-index">TODAS HECHAS EN CASA CON INGREDIENTES FRESCOS <br>Y MUCHO AMOR</P>

    <div class="pizza_index">
      <%@pizzas.each do |pizza|%>
        <ul><%=pizza.name.upcase%>:
        <%=pizza.price%> <i class="fas fa-euro-sign"></i>
        <%=pizza.ingredients%>.
      </ul>

      <%end%>
      </div>
      <p class="subtitle-index">PIZZAS  AL MOLDE DE MEDIA MASA <br> TE RECOMENDAMOS UN PIZZA PARA DOS PERSONAS</p>
      <div class="image_footer">
      <a href="/">
      <%= cl_image_tag("logo_gpvujf",
      width: 100, height:150, ) %>
      </a>
    </div>
  </div>

<%= simple_form_for [@pizza, @order] do |f| %>

      <%= f.association :pizza %> <%= f.input :t_quantity %>
      <%= f.input :customer_name %>
      <%= f.input :customer_lname %>
      <%= f.input :customer_phone %>
      <%= f.input :customer_mail %>
      <%= f.input :customer_street %>
      <%= f.input :customer_floor %>
      <%= f.input :customer_zip %>
      <%= f.input :comment %>
      <%= f.input :delibery_date %>


      <%= f.submit class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
   <button class="btn btn-secondary dropdown-toggle  border-0 py-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-shopping-cart"></i>
    <a href="#" id="cart-notification" class="badge badge-danger cart-number"></a>
  </button>

</div>